# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 10:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, verbose_name='Page Name')),
                ('page_url', models.TextField(validators=[django.core.validators.URLValidator()], verbose_name='Page URL')),
                ('user', models.TextField(verbose_name='User')),
                ('password', fernet_fields.fields.EncryptedTextField(verbose_name='Password')),
            ],
            options={
                'ordering': ('-id'),
            },
        ),
    ]
